version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend-nextjs
    hostname: frontend-nextjs
    volumes:
      - ./frontend:/usr/src/app/frontend
    command: npm run dev
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: backend-flask
    hostname: backend-flask
    volumes:
      - ./backend:/usr/src/app/backend
    command: flask run --host=0.0.0.0